[package]
name = "ssd1963"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-hal = "0.2.5"
packed_struct = { version = "0.5", default_features=false }
stm32f1xx-hal = { version = "0.7.0", optional = true, features = ["stm32f103", "medium"] }

[features]
stm32f1xx = ["stm32f1xx-hal"]
